

library(shiny)
library(ggplot2)
library(dplyr)

#setwd(dirname(rstudioapi::getActiveDocumentContext()$path))

data = read.csv('data/vgsales.csv')
data$Year = as.character(data$Year)

# define ui ----
ui <- fluidPage(
  
  titlePanel("Visualization for Video Game Sales"),
  
  sidebarLayout(
    sidebarPanel(
      selectInput("area", "Choose an Area", 
                         choices = colnames(data)[c(7:11)],
                         selected = 'Global_Sales'),
      sliderInput("year",
                  label = 'Range of Year:',
                  min = 1980, max = 2020, value = c(1980,2020))
      
    ),
    mainPanel(
      h5('The vis is designed to analyze sales data from more than 16,500 games.'),
      h5('This dataset contains a list of video games with sales greater than 100,000 copies. It was generated by a scrape of vgchartz.com.'),
      h5('Data comes from Kaggle'),
      textOutput("selected_var"),
      plotOutput(outputId = "plot1",
                 hover = 'plot_hover')
    
    )
  )
  
  
)


# Define server logic ----
server <- function(input,output){
  
  output$selected_var <- renderText({ 
    paste("The total sales of ", input$area)
  })
  
  output$plot1 <- renderPlot({
    new = data[,c(input$area,'Year','Genre')]
    colnames(new) = c('total','Year','Genre')
    ggplot(new %>% 
             dplyr::filter(Year<=input$year[2] & Year>=input$year[1]) %>%
             dplyr::group_by(Genre) %>%
             dplyr::summarise(sales = sum(total)), 
           aes(x = Genre, y=sales))+
      geom_bar(stat='identity',fill='#6699ff')
  
  })
  
  
}


# Create Shiny app ----
shinyApp(ui = ui, server = server)
 
#runGitHub( "VideoGameVis", "dingluo1205")
